name: Angular Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      xvfb:
        image: electronuserland/electron:latest
        options: --ipc=host

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x' # Set this to your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run lint checks
      run: npm run lint

    - name: Run tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless

    - name: Build project
      run: npm run build -- --prod

    - name: Build Electron application
      run: npm run electron:build # Ensure this script exists in your package.json
